name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  workflow_dispatch: # Also allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Pacman Contribution Graph
        uses: lazy-action/pacman-contribution-graph@main
        with:
          username: Priteshsolanki12
          color: yellow
          output_path: output/pacman-contribution-graph.svg

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add output/pacman-contribution-graph.svg
          git commit -m "Update Pacman contribution graph"
          git push
